### Register User 1
POST http://eldo:9000/auth/register
Content-Type: application/json

{
  "username": "user1",
  "email": "user1@example.com",
  "password": "password1#"
}

### Register User 2
POST http://eldo:9000/auth/register
Content-Type: application/json

{
  "username": "user2",
  "email": "user2@example.com",
  "password": "password2#"
}

### Register User 3
POST http://eldo:9000/auth/register
Content-Type: application/json

{
  "username": "user3",
  "email": "user3@example.com",
  "password": "password3#"
}

### Login User 1
POST http://eldo:9000/auth/login
Content-Type: application/x-www-form-urlencoded

username=user1&password=password1#

### Login User 2
POST http://eldo:9000/auth/login
Content-Type: application/x-www-form-urlencoded

username=user2&password=password2#

### Login User 3
POST http://eldo:9000/auth/login
Content-Type: application/x-www-form-urlencoded

username=user3&password=password3#

### Create a List as User 1
POST http://eldo:9000/lists/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlZTJlMDM2My05NTUxLTQ5OTctYTVlOS05YjZiMWJmYTJmY2YiLCJ1c2VybmFtZSI6InVzZXIxIiwiZW1haWwiOiJ1c2VyMUBleGFtcGxlLmNvbSIsInVzZXJfY3JlYXRlZF9hdCI6IjIwMjUtMDctMDhUMTg6MTc6NDIuMTgzMDYzIiwiZXhwIjoxNzUyMDI2MzkyfQ.0_zHXotzgqI_T3qA5bwOdhAPs5Y8pogEbJQBAccsXsA
Content-Type: application/json

{
  "title": "Groceries"
}

### Share the List with User 2
# Replace {{user1_token}} and {{list_id}} with actual values
POST http://eldo:9000/share/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlZTJlMDM2My05NTUxLTQ5OTctYTVlOS05YjZiMWJmYTJmY2YiLCJ1c2VybmFtZSI6InVzZXIxIiwiZW1haWwiOiJ1c2VyMUBleGFtcGxlLmNvbSIsInVzZXJfY3JlYXRlZF9hdCI6IjIwMjUtMDctMDhUMTg6MTc6NDIuMTgzMDYzIiwiZXhwIjoxNzUyMDI2MzkyfQ.0_zHXotzgqI_T3qA5bwOdhAPs5Y8pogEbJQBAccsXsA
Content-Type: application/json

{
  "list_id": "{{list_id}}",
  "email": "user2@example.com"
}

### List Invites for User 2
GET http://eldo:9000/invites/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyZTNlMTAxMC02ZDE2LTQwODItODRmYy1lOWQ0MmU2NmI3ZTQiLCJ1c2VybmFtZSI6InVzZXIyIiwiZW1haWwiOiJ1c2VyMkBleGFtcGxlLmNvbSIsInVzZXJfY3JlYXRlZF9hdCI6IjIwMjUtMDctMDhUMTg6MTg6NDAuNzMzMTA2IiwiZXhwIjoxNzUyMDI2NDIzfQ.AZ49VJsvb6dnD3ANkn-2-qloDwwaPUAWYWYjOdraRJk

### Accept the Invite as User 2
# Replace {{invite_id}} with actual value
POST http://eldo:9000/invites/{{invite_id}}/accept
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyZTNlMTAxMC02ZDE2LTQwODItODRmYy1lOWQ0MmU2NmI3ZTQiLCJ1c2VybmFtZSI6InVzZXIyIiwiZW1haWwiOiJ1c2VyMkBleGFtcGxlLmNvbSIsInVzZXJfY3JlYXRlZF9hdCI6IjIwMjUtMDctMDhUMTg6MTg6NDAuNzMzMTA2IiwiZXhwIjoxNzUyMDI2NDIzfQ.AZ49VJsvb6dnD3ANkn-2-qloDwwaPUAWYWYjOdraRJk

### Reject the Invite as User 2
# Replace {{invite_id}} with actual value
POST http://eldo:9000/invites/{{invite_id}}/reject
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyZTNlMTAxMC02ZDE2LTQwODItODRmYy1lOWQ0MmU2NmI3ZTQiLCJ1c2VybmFtZSI6InVzZXIyIiwiZW1haWwiOiJ1c2VyMkBleGFtcGxlLmNvbSIsInVzZXJfY3JlYXRlZF9hdCI6IjIwMjUtMDctMDhUMTg6MTg6NDAuNzMzMTA2IiwiZXhwIjoxNzUyMDI2NDIzfQ.AZ49VJsvb6dnD3ANkn-2-qloDwwaPUAWYWYjOdraRJk
