spring.application.name=lists


# TODO: Define Postgress???
spring.datasource.url=jdbc:postgresql://localhost:5432/lists
spring.datasource.username=postgres
# Need to remove this once defined
spring.datasource.password=temp_pass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=9000
spring.jpa.open-in-view=false
spring.data.redis.host=lists-valkey-qkjves.serverless.use2.cache.amazonaws.com
spring.data.redis.port=6379