spring.application.name=lists


# TODO: Define Postgress???
spring.datasource.url=jdbc:postgresql://localhost:5432/lists
spring.datasource.username=postgres
# Need to remove this once defined
spring.datasource.password=temp_pass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=9000
spring.jpa.open-in-view=false
spring.data.redis.host=redis-19749.c325.us-east-1-4.ec2.redns.redis-cloud.com
spring.data.redis.port=19749
spring.data.redis.username=default
spring.data.redis.password=l1ihe17uod5FpNDdi6YKWV1MWorRyoBS
