"""Add ondelete CASCADE to task_list_id

Revision ID: 66cab1a9247a
Revises: 8436bf60d2e9
Create Date: 2025-06-29 19:10:29.525224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66cab1a9247a'
down_revision: Union[str, Sequence[str], None] = '8436bf60d2e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('list_shares_task_list_id_fkey'), 'list_shares', type_='foreignkey')
    op.create_foreign_key(None, 'list_shares', 'task_lists', ['task_list_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('tasks_task_list_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'task_lists', ['task_list_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_task_list_id_fkey'), 'tasks', 'task_lists', ['task_list_id'], ['id'])
    op.drop_constraint(None, 'list_shares', type_='foreignkey')
    op.create_foreign_key(op.f('list_shares_task_list_id_fkey'), 'list_shares', 'task_lists', ['task_list_id'], ['id'])
    # ### end Alembic commands ###
