"""Add quantity column to tasks

Revision ID: 8436bf60d2e9
Revises: 0ab57a08f784
Create Date: 2025-06-29 18:47:19.873785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8436bf60d2e9'
down_revision: Union[str, Sequence[str], None] = '0ab57a08f784'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'quantity')
    # ### end Alembic commands ###
