name: Py Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: lists-backend
          POSTGRES_PASSWORD: password
          POSTGRES_DB: lists-backend-test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      POSTGRES_HOST: localhost
      POSTGRES_DB: lists-backend-test
      POSTGRES_USER: lists-backend
      POSTGRES_PASSWORD: password
      SECRET_KEY: testsecretkey
      PGPORT: 5432
 
      # Add any other env vars needed

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: pip install .
      - name: Run Alembic migrations
        run: alembic upgrade head
      - name: Run tests
        run: pytest