name: Py Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: "sqlite:///./pytest.db"
      # SECRET_KEY: testsecretkey  # Uncomment if your app requires it
      # Add any other env vars needed

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: pip install .
      - name: Run Alembic migrations
        run: alembic upgrade head
      - name: Run tests
        run: pytest